### ISSUE TITLE
Properties not specified in modules?

### ISSUE THREAD

**Issue by zhangyuygss** [davidmascharka/tbd-nets#10]
Hey, I've read the codes for different modules. It seems that the modules does not contain any design for encoding properties (e.g. red or blue for color property). Take `attention` module for example, if we're not sure what color we are attending, how can the module attend to the right locations? Please correct me if I missed something, thanks!

**Comment by davidmascharka** [comment]
Right, there's no design difference between, for example, `attend[red]` and `attend[blue]`. They share the same architecture, but will learn different weights over the course of training. You can see in [this loop](https://github.com/davidmascharka/tbd-nets/blob/master/tbd/module_net.py#L97) that we're adding a module for each of the operations in the CLEVR dataset. Specifically, we'll add [an attention module](https://github.com/davidmascharka/tbd-nets/blob/master/tbd/module_net.py#L119) for `filter[red]` and `filter[blue]` to follow the example above.

So now our module dictionary has a module that is deemed responsible for finding red objects and it has a module deemed responsible for finding blue objects. In every question that I ask about red objects, that same red module is placed into the appropriate location. Similarly, in every question that is asked involving blue objects, the blue module is used. Because the two modules are used in different places and in different questions, they are able to specialize to performing the appropriate operations.

Because the only information the modules are allowed to pass through is a mask, the modules have to learn to pinpoint the location of the relevant objects. To be concrete, the red module *has* to localize red objects in order to perform well at the question answering task because the only information it's allowed to pass is where relevant objects are. If it passes more information than necessary or less information than necessary, the answer will likely be wrong, giving a loss to the red module that pushes it toward correctly identifying red things. In this way, it's able to learn which features from the ResNet module encode the color red and it's able to mask out the locations that do not have this property.
