### ISSUE TITLE
Efficiency question about the model

### ISSUE THREAD

**Issue by zhangyuygss** [davidmascharka/tbd-nets#11]
Hey, I didn't run the code yet. But I noticed the code [module_net.py](https://github.com/davidmascharka/tbd-nets/blob/master/tbd/module_net.py#L173) process questions in a batch one by one, the batch only share the same `stem` and `classifier` module. Although this design is quite reasonable since different questions need different modules, I still worry about the efficiency of the training pharse. What's your setup while training (GPU number, batchsize, training time, etc..)? Do you have some advices on accelerating this? Thanks!

**Comment by davidmascharka** [comment]
Exactly, since the modules aren't the same for each question (and even the *length* of each question varies) we have to construct a question-specific network and forward input one by one. Ultimately, this doesn't become too much of a problem.

I don't recall exactly how long things took, but it was in the neighbourhood of 45 minutes per epoch on CLEVR's 700,000 questions. A safe bet is somewhere between 30 minutes to an hour. The bulk of the work was on two different machines: a server with K80 GPUs and Xeon E5-2698 CPUs and a desktop with 1080TIs and i7-7700K CPU. 

You can see the full training setup [in our notebook](https://github.com/davidmascharka/tbd-nets/blob/master/train-model.ipynb). To summarize: batch size is 128 and we use 2 workers in the PyTorch DataLoader. All of our work was on a single GPU. If training time is a very big concern (you *need* it to take less than the roughly one day training took us) there are some inefficiencies that I'm sure could be improved upon.

Side note: I went ahead and edited your comment to fix the link.

**Comment by zhangyuygss** [comment]
Great, thank you for the answer!
