### ISSUE TITLE
What's the use of cat operation in SameModule

### ISSUE THREAD

**Issue by fangwudi** [davidmascharka/tbd-nets#9]
In SameModule, after the mul of feats and attended_feats，cross-correlation is done. So what's the use of cat operation? cat with attn, does it help?

**Comment by davidmascharka** [comment]
The `Same` module architecture is indeed a bit weird because of the definition of the operation "Same" in CLEVR. An object, by definition, is not the same property as itself. Consider this image:

![](https://cs.stanford.edu/people/jcjohns/clevr/teaser.jpg)

Suppose we want to answer the question "how many objects are the same color as the large shiny sphere?" We'll look at the large shiny sphere and we want to determine how many *other* red things there are. If we just do the cross-correlation, we'll end up with 3 points of attention: the large red sphere, the small red sphere, and the red cylinder. However, CLEVR has defined "same" such that the original object should not be considered; the real answer is that just the small red sphere and the red cylinder are the same color. By concatenating the input attention, our convolutional layer can learn to ignore the original object.

I'm closing this, since it's not a code issue, but feel free to continue the conversation on the closed issue here or via email if you have additional questions.

Edit: for additional discussion, see the Appendix of the arXiv paper; specifically, the paragraph on `Same` can be found on the last page and the penultimate page (pages 10-11).
